version: '3.8'

services:
  backend-inseach:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-inseach
    ports:
      - "5000:5000"
    volumes:
      - /peoogo/docs:/app/inseach   # dossier docs sur le VPS
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: "postgresql://microservices:microservices@ms-postgres:5432/inseach?schema=public"
      JWT_SECRET: "72f21bf2916454b01dd8"
      JWT_ACCESS_EXPIRE: "24h"
      JWT_REFRESH_EXPIRE: "1d"
      COOKIE_EXPIRE: "5d"
      CLOUDINARY_CLOUD_NAME: "dtakbf3ha"
      CLOUDINARY_API_KEY: "196581248868223"
      CLOUDINARY_API_SECRET: "_IN5L1lB4JNqh-t_csNWSb3z5W0"
      FILE_STORAGE_PATH: "/app/docs"
      SERVEUR_URL: "http://109.199.107.23:5000"
    networks:
      - dockerfiles_microservices-net   # r√©seau existant pour DB
    restart: always

networks:
  dockerfiles_microservices-net:
    external: true
